import type { SkillNode } from './schema';

const CANONICAL = ['resume/resume.tex', 'resume/MOHAMMAD_HEYDARI_Full (1).pdf'];
const PROFILE = ['docs/PROFILE.md'];

/**
 * The Brain — knowledge graph nodes. `parent` builds the tree; the graph view adds
 * cross-links from `evidence`. Levels are honest self-assessments justified in docs/PROFILE.md §2.
 */
export const skills: SkillNode[] = [
  {
    id: 'js',
    label: 'JavaScript / TypeScript',
    parent: null,
    category: 'core',
    status: 'expert',
    level: 97,
    description:
      'The root of everything: 10 years across browsers, servers, mobile, and desktop. TypeScript-strict since it existed.',
    evidence: ['portal', 'jackpot', 'vokan', 'septa', 'pezeshket'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'react',
    label: 'React',
    parent: 'js',
    category: 'frontend',
    status: 'expert',
    level: 96,
    description:
      'Primary tool since 2019, through React 19. Architecture-level usage: state isolation, rendering performance, data-heavy UI.',
    evidence: ['portal', 'jackpot', 'pezeshket', 'septa'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'nextjs',
    label: 'Next.js',
    parent: 'react',
    category: 'frontend',
    status: 'expert',
    level: 92,
    description:
      'SSR/ISR/dynamic routing at 540K-user scale at Portal.ir; earlier at Hitobit. Caching strategy as a first-class design tool.',
    evidence: ['portal', 'septa'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'react-native',
    label: 'React Native',
    parent: 'react',
    category: 'frontend',
    status: 'expert',
    level: 90,
    description:
      'From publishing Reqo (2015-19) to Expo 56 New Architecture at VoKaN — including Reanimated gesture-driven UI.',
    evidence: ['vokan', 'reqo', 'septa'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'state',
    label: 'State Architecture',
    parent: 'react',
    category: 'frontend',
    status: 'expert',
    level: 94,
    description:
      'Zustand and custom state engines for financial flows; state isolation that cut Portal.ir production errors ~35%.',
    evidence: ['septa', 'portal', 'jackpot'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'electron',
    label: 'Electron',
    parent: 'react',
    category: 'frontend',
    status: 'working',
    level: 70,
    description: 'Desktop delivery of the Septa Pay shared core.',
    evidence: ['septa'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'node',
    label: 'Node.js',
    parent: 'js',
    category: 'backend',
    status: 'advanced',
    level: 88,
    description:
      'Service-oriented backends, NestJS game engines, SaaS APIs — the systems half of the profile.',
    evidence: ['jackpot', 'portal'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'nestjs',
    label: 'NestJS',
    parent: 'node',
    category: 'backend',
    status: 'advanced',
    level: 84,
    description:
      'The Jackpot engine: server-authoritative game logic, modules, guards, TypeORM integration.',
    evidence: ['jackpot'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'websockets',
    label: 'Real-Time / WebSockets',
    parent: 'node',
    category: 'realtime',
    status: 'advanced',
    level: 88,
    description:
      'Custom binary protocol with shared codec, state recovery and heartbeats; live medical rooms at Pezeshket.',
    evidence: ['jackpot', 'pezeshket'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'concurrency',
    label: 'Concurrency & Parallelism',
    parent: 'node',
    category: 'systems',
    status: 'advanced',
    level: 85,
    description:
      'Redis distributed locking for concurrent spin race conditions; load-tested WebSocket fan-out at 10K connections.',
    evidence: ['jackpot'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'postgres',
    label: 'PostgreSQL',
    parent: 'node',
    category: 'data',
    status: 'advanced',
    level: 82,
    description: 'Relational modeling and consistency via TypeORM in Jackpot; used across roles.',
    evidence: ['jackpot', 'portal'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'redis',
    label: 'Redis',
    parent: 'postgres',
    category: 'data',
    status: 'advanced',
    level: 80,
    description:
      'Caching layers and distributed spin-locks — the difference between "usually right" and "right".',
    evidence: ['jackpot'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'sqlite',
    label: 'SQLite (incl. WASM)',
    parent: 'postgres',
    category: 'data',
    status: 'advanced',
    level: 80,
    description:
      'Offline-first FSRS state in expo-sqlite; SQLite WASM in browsers after solving COOP/COEP isolation.',
    evidence: ['vokan'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'system-design',
    label: 'System Design',
    parent: 'js',
    category: 'systems',
    status: 'advanced',
    level: 87,
    description:
      'HLD focus: modular systems, loose coupling, clear data separation, predictable data flows. Server-authoritative and multi-tenant designs shipped.',
    evidence: ['jackpot', 'portal'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'performance',
    label: 'Performance Engineering',
    parent: 'system-design',
    category: 'systems',
    status: 'advanced',
    level: 85,
    description:
      'SSR/ISR tuning, network-layer optimization, 7K concurrent sessions, 10K-connection load testing.',
    evidence: ['portal', 'pezeshket', 'jackpot'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'docker',
    label: 'Docker & GCP',
    parent: 'system-design',
    category: 'systems',
    status: 'working',
    level: 68,
    description: 'Containerized delivery and Google Cloud deployment across recent roles.',
    evidence: ['portal', 'jackpot'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'ai',
    label: 'AI Engineering',
    parent: 'js',
    category: 'ai',
    status: 'working',
    level: 72,
    description:
      'Production LLM integration: gpt-4o-mini structured outputs, grammar evaluation, caching and fallback queues. The frontier of the map.',
    evidence: ['vokan'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'llm-structured',
    label: 'Structured LLM Outputs',
    parent: 'ai',
    category: 'ai',
    status: 'working',
    level: 75,
    description:
      'JSON-schema-constrained generation with boundary validation — LLMs as dependable components.',
    evidence: ['vokan'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'rag',
    label: 'RAG & Embeddings',
    parent: 'ai',
    category: 'ai',
    status: 'learning',
    level: 40,
    description:
      'Actively learning; this site\u2019s "Talk with Mohammad" assistant is the first working build (chunking, retrieval, guardrails).',
    evidence: ['nexus'],
    sourceRefs: PROFILE,
  },
  {
    id: 'agents',
    label: 'Agents & MCP',
    parent: 'ai',
    category: 'ai',
    status: 'learning',
    level: 30,
    description:
      'Learning agent architectures and the Model Context Protocol; agent-assisted delivery already in the workflow.',
    evidence: ['nexus'],
    sourceRefs: PROFILE,
  },
  {
    id: 'vectordb',
    label: 'Vector Databases',
    parent: 'ai',
    category: 'ai',
    status: 'learning',
    level: 30,
    description:
      'Studying embedding stores and retrieval layouts; current build uses a static local index by design.',
    evidence: ['nexus'],
    sourceRefs: PROFILE,
  },
  {
    id: 'threejs',
    label: 'Three.js / WebGL',
    parent: 'js',
    category: 'frontend',
    status: 'learning',
    level: 45,
    description:
      'The newest branch: this entire world is the learning project — R3F scenes, shaders, instancing, performance budgets.',
    evidence: ['nexus'],
    sourceRefs: PROFILE,
  },
  {
    id: 'leadership',
    label: 'Leadership',
    parent: null,
    category: 'human',
    status: 'advanced',
    level: 86,
    description:
      'Head of Frontend at Septa Pay, Team Lead at Pezeshket and Portal.ir. Facilitation over dictation; structured decision frameworks.',
    evidence: ['septa', 'pezeshket', 'portal'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'mentoring',
    label: 'Mentoring & Review Culture',
    parent: 'leadership',
    category: 'human',
    status: 'advanced',
    level: 84,
    description:
      'Introduced code review practices with performance and quality tracking; mentored junior and mid engineers.',
    evidence: ['pezeshket', 'portal'],
    sourceRefs: CANONICAL,
  },
  {
    id: 'product',
    label: 'Product Thinking',
    parent: null,
    category: 'human',
    status: 'advanced',
    level: 83,
    description:
      'From selling Reqo to shipping VoKaN and Jackpot solo: MVP → scale progression practiced repeatedly, not theorized.',
    evidence: ['reqo', 'vokan', 'jackpot', 'portal'],
    sourceRefs: CANONICAL,
  },
];
